<a href="https://colab.research.google.com/github/JLuisCode/Challenge_AmigoSecreto/blob/main/ChallengeAluraStore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [40]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [34]:
facturacion = {
    "Tienda 1": (tienda["Precio"] * tienda["Cantidad de cuotas"]).sum(),
    "Tienda 2": (tienda2["Precio"] * tienda2["Cantidad de cuotas"]).sum(),
    "Tienda 3": (tienda3["Precio"] * tienda3["Cantidad de cuotas"]).sum(),
    "Tienda 4": (tienda4["Precio"] * tienda4["Cantidad de cuotas"]).sum()
}

pd.Series(facturacion, name="Facturación Total")

Tienda 1    3.422718e+09
Tienda 2    3.337189e+09
Tienda 3    3.243817e+09
Tienda 4    3.098827e+09
Name: Facturación Total, dtype: float64

# 2. Ventas por categoría

In [36]:
categorias_populares = {
    "Tienda 1": tienda["Categoría del Producto"].value_counts().idxmax(),
    "Tienda 2": tienda2["Categoría del Producto"].value_counts().idxmax(),
    "Tienda 3": tienda3["Categoría del Producto"].value_counts().idxmax(),
    "Tienda 4": tienda4["Categoría del Producto"].value_counts().idxmax()
}

pd.Series(categorias_populares, name="Categoría Más Popular")

Tienda 1    Muebles
Tienda 2    Muebles
Tienda 3    Muebles
Tienda 4    Muebles
Name: Categoría Más Popular, dtype: object

# 3. Calificación promedio de la tienda

In [37]:
evaluacion_promedio = {
    "Tienda 1": tienda["Calificación"].mean(),
    "Tienda 2": tienda2["Calificación"].mean(),
    "Tienda 3": tienda3["Calificación"].mean(),
    "Tienda 4": tienda4["Calificación"].mean()
}

pd.Series(evaluacion_promedio, name="Promedio Evaluación")

Tienda 1    3.976685
Tienda 2    4.037304
Tienda 3    4.048326
Tienda 4    3.995759
Name: Promedio Evaluación, dtype: float64

# 4. Productos más y menos vendidos

In [38]:
productos_vendidos = {}

for i, df in enumerate([tienda, tienda2, tienda3, tienda4], 1):
    ventas = df.groupby("Producto")["Cantidad de cuotas"].sum()  # Usar 'Producto' y 'Cantidad de cuotas'
    productos_vendidos[f"Tienda {i} - Más vendido"] = ventas.idxmax()
    productos_vendidos[f"Tienda {i} - Menos vendido"] = ventas.idxmin()

pd.Series(productos_vendidos)

Tienda 1 - Más vendido               Secadora de ropa
Tienda 1 - Menos vendido                 Celular ABXY
Tienda 2 - Más vendido      Iniciando en programación
Tienda 2 - Menos vendido              Mesa de comedor
Tienda 3 - Más vendido                      Bicicleta
Tienda 3 - Menos vendido                TV LED UHD 4K
Tienda 4 - Más vendido        Dashboards con Power BI
Tienda 4 - Menos vendido                      Armario
dtype: object

# 5. Envío promedio por tienda

In [39]:
envio_promedio = {
    "Tienda 1": tienda["Costo de envío"].mean(),
    "Tienda 2": tienda2["Costo de envío"].mean(),
    "Tienda 3": tienda3["Costo de envío"].mean(),
    "Tienda 4": tienda4["Costo de envío"].mean()
}

pd.Series(envio_promedio, name="Promedio Envío")

Tienda 1    26018.609580
Tienda 2    25216.235693
Tienda 3    24805.680373
Tienda 4    23459.457167
Name: Promedio Envío, dtype: float64